#!/bin/bash
# Red AI 2 - Doppler Migration Script
# Generated by Claude Code
# Last Updated: 2025-11-12
#
# SECURITY WARNING: This script contains PLACEHOLDER values only
# DO NOT commit this file with real secrets to version control
#
# Purpose: Migrate environment variables from .env files to Doppler

set -e  # Exit on error

PROJECT="redai2"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}╔════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Red AI 2 - Doppler Secret Migration              ║${NC}"
echo -e "${GREEN}╔════════════════════════════════════════════════════╗${NC}"
echo ""

# Check if Doppler is installed
if ! command -v doppler &> /dev/null; then
    echo -e "${RED}Error: Doppler CLI not found${NC}"
    echo "Install with: curl -Ls https://cli.doppler.com/install.sh | sh"
    exit 1
fi

# Check authentication
if ! doppler me &> /dev/null; then
    echo -e "${RED}Error: Not authenticated with Doppler${NC}"
    echo "Run: doppler login"
    exit 1
fi

echo -e "${YELLOW}IMPORTANT: This script uses PLACEHOLDER values${NC}"
echo -e "${YELLOW}Edit this file and replace placeholders with your actual secrets${NC}"
echo ""
read -p "Have you updated the secrets in this script? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo -e "${RED}Migration cancelled. Update secrets first.${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}Starting migration...${NC}"
echo ""

# ==============================================================================
# DEVELOPMENT ENVIRONMENT
# ==============================================================================

echo -e "${GREEN}[1/3] Migrating to Development (dev)...${NC}"

# Google APIs
doppler secrets set GOOGLE_API_KEY="your_google_api_key_here" \
  --project "$PROJECT" --config dev

doppler secrets set GOOGLE_FILE_SEARCH_STORE_ID="fileSearchStores/your_store_id_here" \
  --project "$PROJECT" --config dev

# Supabase (Development Project)
doppler secrets set SUPABASE_URL="https://your-dev-project.supabase.co" \
  --project "$PROJECT" --config dev

doppler secrets set SUPABASE_ANON_KEY="your_dev_supabase_anon_key_here" \
  --project "$PROJECT" --config dev

doppler secrets set SUPABASE_SERVICE_KEY="your_dev_supabase_service_key_here" \
  --project "$PROJECT" --config dev

# Application Settings
doppler secrets set ENVIRONMENT="development" \
  --project "$PROJECT" --config dev

doppler secrets set PORT="8000" \
  --project "$PROJECT" --config dev

doppler secrets set DEBUG="true" \
  --project "$PROJECT" --config dev

# Batch Processing
doppler secrets set BATCH_API_MODEL="gemini-2.5-flash" \
  --project "$PROJECT" --config dev

doppler secrets set BATCH_API_TEMPERATURE="0.7" \
  --project "$PROJECT" --config dev

doppler secrets set BATCH_API_POLL_INTERVAL="60" \
  --project "$PROJECT" --config dev

# Optional - OpenAI (if enabled)
# doppler secrets set OPENAI_API_KEY="your_openai_api_key_here" \
#   --project "$PROJECT" --config dev

# Optional - Stripe (if enabled)
# doppler secrets set STRIPE_SECRET_KEY="sk_test_your_test_key_here" \
#   --project "$PROJECT" --config dev
# doppler secrets set STRIPE_PUBLISHABLE_KEY="pk_test_your_test_key_here" \
#   --project "$PROJECT" --config dev

echo -e "${GREEN}✓ Development secrets migrated${NC}"
echo ""

# ==============================================================================
# STAGING ENVIRONMENT
# ==============================================================================

echo -e "${GREEN}[2/3] Migrating to Staging (stg)...${NC}"

# Google APIs
doppler secrets set GOOGLE_API_KEY="your_google_api_key_here" \
  --project "$PROJECT" --config stg

doppler secrets set GOOGLE_FILE_SEARCH_STORE_ID="fileSearchStores/your_staging_store_id_here" \
  --project "$PROJECT" --config stg

# Supabase (Staging Project - MUST be separate from dev/prod)
doppler secrets set SUPABASE_URL="https://your-staging-project.supabase.co" \
  --project "$PROJECT" --config stg

doppler secrets set SUPABASE_ANON_KEY="your_staging_supabase_anon_key_here" \
  --project "$PROJECT" --config stg

doppler secrets set SUPABASE_SERVICE_KEY="your_staging_supabase_service_key_here" \
  --project "$PROJECT" --config stg

# Application Settings
doppler secrets set ENVIRONMENT="staging" \
  --project "$PROJECT" --config stg

doppler secrets set PORT="8000" \
  --project "$PROJECT" --config stg

doppler secrets set DEBUG="false" \
  --project "$PROJECT" --config stg

# Batch Processing
doppler secrets set BATCH_API_MODEL="gemini-2.5-flash" \
  --project "$PROJECT" --config stg

doppler secrets set BATCH_API_TEMPERATURE="0.7" \
  --project "$PROJECT" --config stg

doppler secrets set BATCH_API_POLL_INTERVAL="60" \
  --project "$PROJECT" --config stg

echo -e "${GREEN}✓ Staging secrets migrated${NC}"
echo ""

# ==============================================================================
# PRODUCTION ENVIRONMENT
# ==============================================================================

echo -e "${GREEN}[3/3] Migrating to Production (prd)...${NC}"

# Google APIs (Production)
doppler secrets set GOOGLE_API_KEY="your_production_google_api_key_here" \
  --project "$PROJECT" --config prd

doppler secrets set GOOGLE_FILE_SEARCH_STORE_ID="fileSearchStores/your_production_store_id_here" \
  --project "$PROJECT" --config prd

# Supabase (Production Project - MUST be separate from dev/staging)
doppler secrets set SUPABASE_URL="https://your-production-project.supabase.co" \
  --project "$PROJECT" --config prd

doppler secrets set SUPABASE_ANON_KEY="your_production_supabase_anon_key_here" \
  --project "$PROJECT" --config prd

doppler secrets set SUPABASE_SERVICE_KEY="your_production_supabase_service_key_here" \
  --project "$PROJECT" --config prd

# Application Settings
doppler secrets set ENVIRONMENT="production" \
  --project "$PROJECT" --config prd

doppler secrets set PORT="8000" \
  --project "$PROJECT" --config prd

doppler secrets set DEBUG="false" \
  --project "$PROJECT" --config prd

# Batch Processing
doppler secrets set BATCH_API_MODEL="gemini-2.5-flash" \
  --project "$PROJECT" --config prd

doppler secrets set BATCH_API_TEMPERATURE="0.7" \
  --project "$PROJECT" --config prd

doppler secrets set BATCH_API_POLL_INTERVAL="60" \
  --project "$PROJECT" --config prd

# Optional - OpenAI (if enabled in production)
# doppler secrets set OPENAI_API_KEY="your_production_openai_api_key_here" \
#   --project "$PROJECT" --config prd

# Optional - Stripe (if enabled in production)
# doppler secrets set STRIPE_SECRET_KEY="sk_live_your_live_secret_key_here" \
#   --project "$PROJECT" --config prd
# doppler secrets set STRIPE_PUBLISHABLE_KEY="pk_live_your_live_publishable_key_here" \
#   --project "$PROJECT" --config prd
# doppler secrets set STRIPE_WEBHOOK_SECRET="whsec_your_production_webhook_secret_here" \
#   --project "$PROJECT" --config prd

echo -e "${GREEN}✓ Production secrets migrated${NC}"
echo ""

# ==============================================================================
# SUMMARY
# ==============================================================================

echo -e "${GREEN}╔════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Migration Complete!                               ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Verify secrets:"
echo "  Development:  doppler secrets --project $PROJECT --config dev"
echo "  Staging:      doppler secrets --project $PROJECT --config stg"
echo "  Production:   doppler secrets --project $PROJECT --config prd"
echo ""
echo "Next steps:"
echo "  1. Test locally:    doppler run --project $PROJECT --config dev -- uvicorn api.main:app"
echo "  2. Clean old .env:  trash-put .env.development .env.staging .env.production"
echo "  3. Setup CI/CD:     https://dashboard.doppler.com/workplace/projects/$PROJECT"
echo ""
echo -e "${YELLOW}SECURITY: After migration, safely delete old .env files${NC}"
echo -e "${YELLOW}They are no longer needed and may contain outdated secrets${NC}"
