#!/bin/bash
# Red AI 2 - Doppler Run Wrapper
# Generated by Claude Code
# Last Updated: 2025-11-12
#
# Purpose: Convenient wrapper to run commands with Doppler secrets

set -e

PROJECT="redai2"
DEFAULT_CONFIG="dev"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Parse config from arguments or use default
CONFIG="${DOPPLER_CONFIG:-$DEFAULT_CONFIG}"

# Show usage if no command provided
if [ $# -eq 0 ]; then
    echo -e "${YELLOW}Usage: ./run-with-doppler.sh [command]${NC}"
    echo ""
    echo "Examples:"
    echo "  Backend:   ./run-with-doppler.sh uvicorn api.main:app --reload"
    echo "  Frontend:  DOPPLER_CONFIG=dev ./run-with-doppler.sh npm run dev"
    echo "  Scripts:   ./run-with-doppler.sh python backend/scripts/setup_file_search.py"
    echo ""
    echo "Environment selection:"
    echo "  Development (default):  ./run-with-doppler.sh [command]"
    echo "  Staging:                DOPPLER_CONFIG=stg ./run-with-doppler.sh [command]"
    echo "  Production:             DOPPLER_CONFIG=prd ./run-with-doppler.sh [command]"
    echo ""
    echo "Current config: $CONFIG"
    exit 1
fi

echo -e "${GREEN}Running with Doppler ($CONFIG)...${NC}"

# Run command with Doppler
doppler run --project "$PROJECT" --config "$CONFIG" -- "$@"
