#!/bin/bash
# Red AI 2 - Doppler GitHub Integration Setup
# Generated by Claude Code
# Last Updated: 2025-11-12

set -e

PROJECT="redai2"
GITHUB_REPO="vanman2024/redai2"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}╔════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Red AI 2 - Doppler GitHub Integration Setup      ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════╝${NC}"
echo ""

# Check Doppler authentication
if ! doppler me &> /dev/null; then
    echo -e "${RED}Error: Not authenticated with Doppler${NC}"
    echo "Run: doppler login"
    exit 1
fi

echo -e "${BLUE}GitHub Repository:${NC} $GITHUB_REPO"
echo -e "${BLUE}Doppler Project:${NC} $PROJECT"
echo ""

# Step 1: Install GitHub Integration (Manual)
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}Step 1: Install Doppler GitHub App${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "The GitHub integration must be installed through the Doppler Dashboard."
echo ""
echo -e "${GREEN}Opening Doppler integrations page in your browser...${NC}"
echo ""

# Open integrations page
INTEGRATIONS_URL="https://dashboard.doppler.com/workplace/projects/$PROJECT/integrations"
echo -e "${BLUE}URL:${NC} $INTEGRATIONS_URL"
echo ""

# Try to open in browser
if command -v xdg-open &> /dev/null; then
    xdg-open "$INTEGRATIONS_URL" 2>/dev/null || true
elif command -v open &> /dev/null; then
    open "$INTEGRATIONS_URL" 2>/dev/null || true
else
    echo -e "${YELLOW}Please open this URL manually:${NC}"
    echo "$INTEGRATIONS_URL"
fi

echo ""
echo -e "${GREEN}Follow these steps in the dashboard:${NC}"
echo ""
echo "1. Click 'GitHub' in the integrations list"
echo "2. Click 'Install Integration'"
echo "3. Authorize Doppler GitHub App"
echo "4. Select repository: $GITHUB_REPO"
echo "5. Click 'Install & Authorize'"
echo ""

read -p "Press ENTER after completing GitHub App installation..."

# Step 2: Configure Sync Mappings
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}Step 2: Configure Sync Mappings${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Configure sync mappings for each environment:"
echo ""

echo -e "${GREEN}Development Environment:${NC}"
echo "  Doppler Config:     dev"
echo "  GitHub Environment: development"
echo "  Repository:         $GITHUB_REPO"
echo ""

echo -e "${GREEN}Staging Environment:${NC}"
echo "  Doppler Config:     stg"
echo "  GitHub Environment: staging"
echo "  Repository:         $GITHUB_REPO"
echo ""

echo -e "${GREEN}Production Environment:${NC}"
echo "  Doppler Config:     prd"
echo "  GitHub Environment: production"
echo "  Repository:         $GITHUB_REPO"
echo ""

echo "The sync configuration page should now be visible in your browser."
echo "Add each mapping and click 'Save' for each one."
echo ""

read -p "Press ENTER after configuring all sync mappings..."

# Step 3: Create GitHub Environments
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}Step 3: Create GitHub Environments${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

GITHUB_ENV_URL="https://github.com/$GITHUB_REPO/settings/environments"
echo -e "${BLUE}Opening GitHub Environments page...${NC}"
echo -e "${BLUE}URL:${NC} $GITHUB_ENV_URL"
echo ""

if command -v xdg-open &> /dev/null; then
    xdg-open "$GITHUB_ENV_URL" 2>/dev/null || true
elif command -v open &> /dev/null; then
    open "$GITHUB_ENV_URL" 2>/dev/null || true
else
    echo -e "${YELLOW}Please open this URL manually:${NC}"
    echo "$GITHUB_ENV_URL"
fi

echo ""
echo -e "${GREEN}Create these environments in GitHub:${NC}"
echo ""
echo "1. Click 'New environment'"
echo "   Name: development"
echo "   Click 'Configure environment'"
echo ""
echo "2. Click 'New environment'"
echo "   Name: staging"
echo "   Click 'Configure environment'"
echo ""
echo "3. Click 'New environment'"
echo "   Name: production"
echo "   ✓ Enable 'Required reviewers'"
echo "   Add yourself as reviewer"
echo "   Click 'Save protection rules'"
echo ""

read -p "Press ENTER after creating all GitHub environments..."

# Step 4: Verify Sync
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}Step 4: Verify Secret Sync${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

GITHUB_SECRETS_URL="https://github.com/$GITHUB_REPO/settings/secrets/actions"
echo -e "${BLUE}Opening GitHub Secrets page...${NC}"
echo -e "${BLUE}URL:${NC} $GITHUB_SECRETS_URL"
echo ""

if command -v xdg-open &> /dev/null; then
    xdg-open "$GITHUB_SECRETS_URL" 2>/dev/null || true
elif command -v open &> /dev/null; then
    open "$GITHUB_SECRETS_URL" 2>/dev/null || true
else
    echo -e "${YELLOW}Please open this URL manually:${NC}"
    echo "$GITHUB_SECRETS_URL"
fi

echo ""
echo -e "${GREEN}Verify secrets are synced:${NC}"
echo ""
echo "1. Click 'Environment secrets' tab"
echo "2. Select 'development' environment"
echo "3. You should see secrets from Doppler dev config:"
echo "   - GOOGLE_API_KEY"
echo "   - GOOGLE_FILE_SEARCH_STORE_ID"
echo "   - SUPABASE_URL"
echo "   - SUPABASE_ANON_KEY"
echo "   - SUPABASE_SERVICE_KEY"
echo "   - ENVIRONMENT"
echo "   - PORT"
echo "   - DEBUG"
echo "   - BATCH_API_MODEL"
echo "   - BATCH_API_TEMPERATURE"
echo "   - BATCH_API_POLL_INTERVAL"
echo ""
echo "4. Repeat for 'staging' and 'production' environments"
echo ""

read -p "Press ENTER if secrets are visible in GitHub..."

# Summary
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  GitHub Integration Setup Complete!                ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${GREEN}✓ Doppler GitHub App installed${NC}"
echo -e "${GREEN}✓ Sync mappings configured${NC}"
echo -e "${GREEN}✓ GitHub Environments created${NC}"
echo -e "${GREEN}✓ Secrets syncing automatically${NC}"
echo ""

echo -e "${BLUE}What happens now:${NC}"
echo "  • Update secrets in Doppler → Auto-syncs to GitHub (~1 minute)"
echo "  • GitHub Actions workflows use: environment: staging/production"
echo "  • Secrets available via: \${{ secrets.SECRET_NAME }}"
echo ""

echo -e "${BLUE}Next steps:${NC}"
echo "  1. Update GitHub Actions workflows (see examples in docs/doppler/)"
echo "  2. Test with: .github/workflows/test-secrets.yml (create this)"
echo "  3. Enable production protection rules (requires approval)"
echo ""

echo -e "${BLUE}Documentation:${NC}"
echo "  • Integration Guide:  docs/doppler/integration-guide.md"
echo "  • GitHub Setup:       docs/doppler/github-integration.md"
echo "  • Environment Setup:  docs/doppler/environment-setup.md"
echo ""

echo -e "${YELLOW}Remember: After migrating secrets to Doppler${NC}"
echo -e "${YELLOW}(edit migrate-to-doppler.sh), they'll auto-sync to GitHub!${NC}"
